### ISSUE TITLE
Does not work with WP Version 4.7.3 & Mautic v2.7.1

### ISSUE THREAD

**Issue by yashodhank** [brainstormforce/automate-mautic#13]
I tried plugin and configured API properly, authenticated with OAuth2 and triggers but never it never updated newly registered users or commenters to Mautic.
Have I don't something wrong? or does this plugin have compatibility issue with latest mautic version?

**Comment by rahulwalunje** [comment]
I tested plugin by registering user and commenting on post with same versions you specified and its working as expected. Please try registering user form other browser ( where you are not logged in to Mautic  ) so that there will no logged in mautic cookie will be stored.
